### PR TITLE
Browser friendly errors (<pre> instead of alert)

### PR DESCRIPTION
**Pull request by zertosh**
See https://github.com/zertosh/errorify/issues/1

### CODE REVIEW

**Comment by mattdesl** [comment]
Nice turnaround. :+1: 

The `err_` isn't getting used so it just ends up reporting an empty object.

Also now that I've been trying it out, I'm wondering if the stack just adds too much unrelated clutter/noise. Especially with babelify transform, it starts to look weird. 

screen shot 2015-03-22 at 6 58 57 pm

## 

Compare with just using `err.message` and making the element red:

screen shot 2015-03-22 at 6 57 49 pm

**Comment by mattdesl** [comment]
Also for some reason it looks like browserify 9 is not giving lineNumber and other details. Just message, type and stack.

**Comment by zertosh** [comment]
Woops, I missed the `err_`.

Depends on what threw the error, it'll have certain details. Like when a `require` doesn't exist, it's usually a very unhelpful error. But, I agree that the stack is kinda over-kill.

My concern with including styles is that: (1) they would have to be inlined, which means you can't really have your own debug css styles - like `body > .errorify` (I'm going to add that class), and (2) you might have css already that correctly loaded, that'll make the error text illegible.

**Comment by zertosh** [comment]
Wow... good call on this whole `<pre>` thing!!!

yvuek

``` css
/* DEBUG STYLES */
body > .errorify {
  color: red;
  background: #222;
  padding: 20px;
  position: absolute;
  top: 0; right: 0; bottom: 0; left: 0; 
}
```

**Comment by mattdesl** [comment]
Yeah, Babel's error reporting is amazing.

The class name approach sounds good. :+1:

**Comment by zertosh** [comment]
Published as `errorify@0.1.0`

**Pull request merged**
